[2023-05-14T00:51:44.821+0000] {processor.py:153} INFO - Started process (PID=40) to work on /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:51:44.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/upload_data_to_gcs.py for tasks to queue
[2023-05-14T00:51:44.825+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:51:44.824+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:51:44.847+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:51:44.844+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/upload_data_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_data_to_gcs.py", line 6, in <module>
    from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
ModuleNotFoundError: No module named 'airflow.providers.microsoft.mssql'
[2023-05-14T00:51:44.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:51:44.884+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/upload_data_to_gcs.py took 0.067 seconds
[2023-05-14T00:52:15.209+0000] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:15.212+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/upload_data_to_gcs.py for tasks to queue
[2023-05-14T00:52:15.215+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:52:15.214+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:15.264+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:52:15.262+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/upload_data_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_data_to_gcs.py", line 6, in <module>
    from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
ModuleNotFoundError: No module named 'airflow.providers.microsoft.mssql'
[2023-05-14T00:52:15.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:15.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/upload_data_to_gcs.py took 0.089 seconds
[2023-05-14T00:52:45.761+0000] {processor.py:153} INFO - Started process (PID=67) to work on /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:45.764+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/upload_data_to_gcs.py for tasks to queue
[2023-05-14T00:52:45.765+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:52:45.765+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:45.802+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:52:45.799+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/upload_data_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_data_to_gcs.py", line 6, in <module>
    from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
ModuleNotFoundError: No module named 'airflow.providers.microsoft.mssql'
[2023-05-14T00:52:45.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:52:45.830+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/upload_data_to_gcs.py took 0.075 seconds
[2023-05-14T00:53:16.280+0000] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:16.282+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/upload_data_to_gcs.py for tasks to queue
[2023-05-14T00:53:16.283+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:53:16.283+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:16.310+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:53:16.308+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/upload_data_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_data_to_gcs.py", line 6, in <module>
    from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
ModuleNotFoundError: No module named 'airflow.providers.microsoft.mssql'
[2023-05-14T00:53:16.311+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:16.333+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/upload_data_to_gcs.py took 0.059 seconds
[2023-05-14T00:53:46.764+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:46.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/upload_data_to_gcs.py for tasks to queue
[2023-05-14T00:53:46.771+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:53:46.771+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:46.820+0000] {logging_mixin.py:137} INFO - [2023-05-14T00:53:46.813+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/upload_data_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_data_to_gcs.py", line 6, in <module>
    from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook
ModuleNotFoundError: No module named 'airflow.providers.microsoft.mssql'
[2023-05-14T00:53:46.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_data_to_gcs.py
[2023-05-14T00:53:46.846+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/upload_data_to_gcs.py took 0.091 seconds
